# Generated by Django 4.1.6 on 2023-02-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixieapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
