steps:
  - name: gcr.io/cloud-builders/git
    args:
      - "-c"
      - |
        echo "$$SSHKEY" > /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        ssh-keyscan ${_GITLAB_IP} > /root/.ssh/known_hosts
    entrypoint: bash
    secretEnv:
      - SSHKEY
    volumes:
      - name: ssh
        path: /root/.ssh
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - "git@${_GITLAB_IP}:${_GITLAB_NAME}.git"
      - .
    volumes:
      - name: ssh
        path: /root/.ssh
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "${_ARTIFACT_REPO}"
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "${_ARTIFACT_REPO}"
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - my-service
      - "--image"
      - "${_ARTIFACT_REPO}"
      - "--region"
      - us-central1
      - "--allow-unauthenticated"
    entrypoint: gcloud
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _PROJECT_NUMBER: "231184914133"
  _GITLAB_IP: 34.139.157.79
  _ARTIFACT_REPO: "us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO_NAME}/myimg"
  _GITLAB_NAME: andrewadcock/pixie
  _ARTIFACT_REPO_NAME: my-repo
availableSecrets:
  secretManager:
    - versionName: "projects/${_PROJECT_NUMBER}/secrets/gitlab-key/versions/1"
      env: SSHKEY
