version: "3.9"
   
services:
  db:
    container_name: postgres_container
    image: postgres
    volumes:
      - ./data/:/var/lib/postgresql/data
    env_file: ./db/.env
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
  backend:
    build:
      context: ./backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pixie-data:
  pixie-backend-code: