repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
#  - repo: https://github.com/pycqa/flake8
#    rev: '4.0.1'
#    hooks:
#      - id: flake8
