import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useContext } from "react";
import UserContext from "@/context/authentication";

export default function Home() {
  const { user } = useContext(UserContext);

  console.log("userCtx", user);

  return (
    <>
      <Head>
        <title>Pixie - The Movie Picking Aid</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Home
        {user.first_name ? (
          `Welcome ${user.first_name}`
        ) : (
          <a href={"/account/login/"}>Please log in</a>
        )}
      </main>
    </>
  );
}
